---
version: '3.8'

services:
  jammy-runner:
    image: ghcr.io/missourimrdt/jammy-runner:latest
    build:
      context: .
      dockerfile: Dockerfile_Jammy
      args:
        RUNNER_VERSION: '2.310.2'
    command: unix-connect:/var/run/docker.sock
    deploy:
      replicas: 2
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      GH_TOKEN: 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
      GH_OWNER: MissouriMRDT
      GH_REPOSITORY: Autonomy_Software

  jetpack-runner:
    image: ghcr.io/missourimrdt/jetpack-runner:latest
    build:
      context: .
      dockerfile: Dockerfile_JetPack
      args:
        RUNNER_VERSION: '2.310.2'
    command: unix-connect:/var/run/docker.sock
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      GH_TOKEN: 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
      GH_OWNER: MissouriMRDT
      GH_REPOSITORY: Autonomy_Software

